source ${HOME}/.scripts/zsh/src/envs.sh
source ${HOME}/.scripts/zsh/src/utils.sh
source ${HOME}/.scripts/zsh/src/nvm.sh
source ${HOME}/.scripts/zsh/src/docker.sh
source ${HOME}/.scripts/zsh/src/git.sh
source ${HOME}/.scripts/zsh/src/aliases.sh
source ${HOME}/.scripts/zsh/src/nvim.sh
source ${HOME}/.scripts/zsh/src/scripts.sh
source ${HOME}/.scripts/zsh/src/ssh.sh
